apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact-attestations-opa-provider
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: artifact-attestations-opa-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: artifact-attestations-opa-provider
        {{- if .Values.azureClientId }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      automountServiceAccountToken: true
      containers:
      - image: ghcr.io/github/artifact-attestations-opa-provider:dev
        imagePullPolicy: IfNotPresent
        name: artifact-attestations-opa-provider
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
        args:
        - -namespace={{ .Release.Namespace }}
        - -image-pull-secret={{ .Values.imagePullSecrets }}
        - -certs={{ .Values.certDir }}
        - -port={{ .Values.port }}
        - -trust-domain={{ .Values.trustDomain }}
        - -update-ca-bundle={{ .Values.provider.tls.updateCABundle }}
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        # Prevent container from shutting down before kube-proxy has converged
        lifecycle:
          preStop:
            exec:
              command: [ "sleep", "5" ]
        readinessProbe:
          httpGet:
            port: {{ .Values.port }}
            path: "/readyz"
            scheme: HTTPS
        volumeMounts:
        - name: provider-tls-cert
          mountPath: {{ .Values.certDir }}
          readOnly: true
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: provider-tls-cert
        secret:
          secretName: provider-tls-cert
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
{{- if .Values.provider.tls.updateCABundle }}
            - key: ca.crt
              path: ca.crt
{{- end }}
