{{- if .Values.provider.tls.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: artifact-attestations-opa-provider-self-signed
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: artifact-attestations-opa-provider-self-signed
  namespace: {{ .Release.Namespace }}
spec:
  commonName: artifact-attestations-opa-provider-self-signed
  issuerRef:
    name: artifact-attestations-opa-provider-self-signed
  secretName: artifact-attestations-opa-provider-self-signed
  isCA: true
  duration: 4320h # 180 days
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "artifact-attestations-opa-provider"
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: artifact-attestations-opa-provider-self-signed
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: artifact-attestations-opa-provider
  namespace: {{ .Release.Namespace }}
spec:
  secretName: provider-tls-cert
  duration: 2160h # 90 days
  issuerRef:
    name: "artifact-attestations-opa-provider"
  dnsNames:
  - artifact-attestations-opa-provider
  - artifact-attestations-opa-provider.{{ .Release.Namespace }}
  - artifact-attestations-opa-provider.{{ .Release.Namespace }}.svc
  - artifact-attestations-opa-provider.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
