apiVersion: externaldata.gatekeeper.sh/v1beta1
kind: Provider
metadata:
  name: artifact-attestations-opa-provider
spec:
  url: https://artifact-attestations-opa-provider.{{ .Release.Namespace }}:{{ .Values.port }}
  timeout: {{ .Values.provider.timeout }}
  {{- if .Values.provider.tls.caBundle }}
  caBundle: {{ .Values.provider.tls.caBundle }}
  {{- else if not .Values.provider.tls.useCertManager }}
  {{- fail "You must set either .Values.provider.tls.caBundle or .Values.provider.tls.useCertManager" }}
  {{- end }}
