name: Integration tests

on:
  push:
    branches:
      - main
  pull_request: {}

permissions: {}

jobs:
  test:
    name: Integration test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - name: Build
        run: |
          make build
      - name: Generate certificates
        env:
          HOST: localhost
        run: |
          ./scripts/gen_certs.sh
      - name: Run tests
        run: |
          ./scripts/integration_test.sh
