name: Test rego examples

on:
  push:
    branches:
      - main
  pull_request: {}

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@950f159a49aa91f9323f36f1de81c7f6b5de9576 # 2.3.0
        with:
          version: latest
      - name: Test
        run: |
          make test-rego
      - name: Verify constraint files
        shell: bash
        run: |
          ./scripts/diff_policy.sh
